### ISSUE TITLE
Please help with dero golang pool

### ISSUE THREAD

**Issue by ChaoLine892** [Nelbert442/dero-smartcontracts#1]
Please answer, I'm about the dero golang pool. I have errors when connecting dero daemon which I presented below
`[Blocks] Error while refreshing block template: json: cannot unmarshal string into Go struct field GetBlockTemplateReply.difficulty of type uint64`
and
`2023/11/09 23:01:40.576696 [Graviton] ERROR: Probably data corruption, unknown node type
2023/11/09 23:01:40.578694 [Graviton] ERROR: Probably data corruption, unknown node type`
Please tell me is it not daemon compatibility or am I doing something wrong...

**Comment by Nelbert442** [comment]
[dero-golang-pool](https://github.com/Nelbert442/dero-golang-pool) is no longer supported and was archived some time ago.
